# -----------------------------
# -----------------------------
spring.application.name=backinexus
spring.main.web-application-type=servlet

# -----------------------------
# -----------------------------
spring.output.ansi.enabled=ALWAYS
spring.cache.type=none
spring.jackson.default-property-inclusion=NON_NULL
spring.jackson.deserialization.fail-on-unknown-properties=false

# -----------------------------
# JWT se valida con clave secreta en WebFlux (no Firebase)
# -----------------------------
# Elimina esto si usas JWT local, no Firebase
# spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/base-app-weather

# -----------------------------
# -----------------------------
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
logging.level.org.springframework.http.codec=TRACE
logging.level.com.kinexus=DEBUG

# -----------------------------
# Base de datos PostgreSQL
# -----------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/bdkinexus
spring.datasource.username=btobar
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# -----------------------------

# -----------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
